version: '3.8'

services:
  interrapidisimoapi:
    build:
      context: .
      dockerfile: ./InterRapidisimoApi/Dockerfile
    container_name: interrapidisimo-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Server=sqlserver;Database=InterDb;User=sa;Password=Y0k0gawA_19929495;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
        - interNetwork

  # Servicio de SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Y0k0gawA_19929495
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - interNetwork

volumes:
  sqlvolume:

networks:
  interNetwork:
    driver: bridge
